################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (9-2020-q2-update)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
C:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Utilities/GUI_INTERFACE/bsp_gui.c \
C:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Utilities/GUI_INTERFACE/data_struct_tlv.c \
C:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Utilities/GUI_INTERFACE/gui_api.c \
C:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Utilities/TRACER_EMB/tracer_emb.c \
C:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Utilities/TRACER_EMB/tracer_emb_hw.c 

OBJS += \
./Utilities/bsp_gui.o \
./Utilities/data_struct_tlv.o \
./Utilities/gui_api.o \
./Utilities/tracer_emb.o \
./Utilities/tracer_emb_hw.o 

C_DEPS += \
./Utilities/bsp_gui.d \
./Utilities/data_struct_tlv.d \
./Utilities/gui_api.d \
./Utilities/tracer_emb.d \
./Utilities/tracer_emb_hw.d 


# Each subdirectory must supply rules for building sources it contributes
Utilities/bsp_gui.o: C:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Utilities/GUI_INTERFACE/bsp_gui.c Utilities/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32G071xx -DUSE_FULL_LL_DRIVER '-DUSBPD_PORT_COUNT=1' -D_RTOS -D_SNK -D_TRACE -D_GUI_INTERFACE -DUSBPDCORE_LIB_PD3_FULL -c -I../Core/Inc -I../USBPD/App -I../USBPD -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Drivers/STM32G0xx_HAL_Driver/Inc -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Drivers/STM32G0xx_HAL_Driver/Inc/Legacy -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Utilities/GUI_INTERFACE -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Utilities/TRACER_EMB -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Middlewares/Third_Party/FreeRTOS/Source/include -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM0 -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Middlewares/ST/STM32_USBPD_Library/Core/inc -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Middlewares/ST/STM32_USBPD_Library/Devices/STM32G0XX/inc -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Drivers/CMSIS/Device/ST/STM32G0xx/Include -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Utilities/bsp_gui.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Utilities/data_struct_tlv.o: C:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Utilities/GUI_INTERFACE/data_struct_tlv.c Utilities/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32G071xx -DUSE_FULL_LL_DRIVER '-DUSBPD_PORT_COUNT=1' -D_RTOS -D_SNK -D_TRACE -D_GUI_INTERFACE -DUSBPDCORE_LIB_PD3_FULL -c -I../Core/Inc -I../USBPD/App -I../USBPD -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Drivers/STM32G0xx_HAL_Driver/Inc -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Drivers/STM32G0xx_HAL_Driver/Inc/Legacy -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Utilities/GUI_INTERFACE -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Utilities/TRACER_EMB -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Middlewares/Third_Party/FreeRTOS/Source/include -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM0 -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Middlewares/ST/STM32_USBPD_Library/Core/inc -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Middlewares/ST/STM32_USBPD_Library/Devices/STM32G0XX/inc -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Drivers/CMSIS/Device/ST/STM32G0xx/Include -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Utilities/data_struct_tlv.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Utilities/gui_api.o: C:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Utilities/GUI_INTERFACE/gui_api.c Utilities/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32G071xx -DUSE_FULL_LL_DRIVER '-DUSBPD_PORT_COUNT=1' -D_RTOS -D_SNK -D_TRACE -D_GUI_INTERFACE -DUSBPDCORE_LIB_PD3_FULL -c -I../Core/Inc -I../USBPD/App -I../USBPD -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Drivers/STM32G0xx_HAL_Driver/Inc -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Drivers/STM32G0xx_HAL_Driver/Inc/Legacy -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Utilities/GUI_INTERFACE -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Utilities/TRACER_EMB -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Middlewares/Third_Party/FreeRTOS/Source/include -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM0 -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Middlewares/ST/STM32_USBPD_Library/Core/inc -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Middlewares/ST/STM32_USBPD_Library/Devices/STM32G0XX/inc -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Drivers/CMSIS/Device/ST/STM32G0xx/Include -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Utilities/gui_api.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Utilities/tracer_emb.o: C:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Utilities/TRACER_EMB/tracer_emb.c Utilities/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32G071xx -DUSE_FULL_LL_DRIVER '-DUSBPD_PORT_COUNT=1' -D_RTOS -D_SNK -D_TRACE -D_GUI_INTERFACE -DUSBPDCORE_LIB_PD3_FULL -c -I../Core/Inc -I../USBPD/App -I../USBPD -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Drivers/STM32G0xx_HAL_Driver/Inc -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Drivers/STM32G0xx_HAL_Driver/Inc/Legacy -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Utilities/GUI_INTERFACE -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Utilities/TRACER_EMB -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Middlewares/Third_Party/FreeRTOS/Source/include -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM0 -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Middlewares/ST/STM32_USBPD_Library/Core/inc -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Middlewares/ST/STM32_USBPD_Library/Devices/STM32G0XX/inc -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Drivers/CMSIS/Device/ST/STM32G0xx/Include -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Utilities/tracer_emb.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Utilities/tracer_emb_hw.o: C:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Utilities/TRACER_EMB/tracer_emb_hw.c Utilities/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32G071xx -DUSE_FULL_LL_DRIVER '-DUSBPD_PORT_COUNT=1' -D_RTOS -D_SNK -D_TRACE -D_GUI_INTERFACE -DUSBPDCORE_LIB_PD3_FULL -c -I../Core/Inc -I../USBPD/App -I../USBPD -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Drivers/STM32G0xx_HAL_Driver/Inc -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Drivers/STM32G0xx_HAL_Driver/Inc/Legacy -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Utilities/GUI_INTERFACE -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Utilities/TRACER_EMB -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Middlewares/Third_Party/FreeRTOS/Source/include -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM0 -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Middlewares/ST/STM32_USBPD_Library/Core/inc -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Middlewares/ST/STM32_USBPD_Library/Devices/STM32G0XX/inc -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Drivers/CMSIS/Device/ST/STM32G0xx/Include -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Utilities/tracer_emb_hw.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"

