################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (9-2020-q2-update)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
C:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Middlewares/ST/STM32_USBPD_Library/Devices/STM32G0XX/src/usbpd_cad_hw_if.c \
C:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Middlewares/ST/STM32_USBPD_Library/Devices/STM32G0XX/src/usbpd_hw.c \
C:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Middlewares/ST/STM32_USBPD_Library/Devices/STM32G0XX/src/usbpd_hw_if_it.c \
C:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Middlewares/ST/STM32_USBPD_Library/Devices/STM32G0XX/src/usbpd_phy.c \
C:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Middlewares/ST/STM32_USBPD_Library/Devices/STM32G0XX/src/usbpd_phy_hw_if.c \
C:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Middlewares/ST/STM32_USBPD_Library/Devices/STM32G0XX/src/usbpd_pwr_hw_if.c \
C:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Middlewares/ST/STM32_USBPD_Library/Devices/STM32G0XX/src/usbpd_timersserver.c \
C:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Middlewares/ST/STM32_USBPD_Library/Core/src/usbpd_trace.c 

OBJS += \
./Middlewares/USBPD/usbpd_cad_hw_if.o \
./Middlewares/USBPD/usbpd_hw.o \
./Middlewares/USBPD/usbpd_hw_if_it.o \
./Middlewares/USBPD/usbpd_phy.o \
./Middlewares/USBPD/usbpd_phy_hw_if.o \
./Middlewares/USBPD/usbpd_pwr_hw_if.o \
./Middlewares/USBPD/usbpd_timersserver.o \
./Middlewares/USBPD/usbpd_trace.o 

C_DEPS += \
./Middlewares/USBPD/usbpd_cad_hw_if.d \
./Middlewares/USBPD/usbpd_hw.d \
./Middlewares/USBPD/usbpd_hw_if_it.d \
./Middlewares/USBPD/usbpd_phy.d \
./Middlewares/USBPD/usbpd_phy_hw_if.d \
./Middlewares/USBPD/usbpd_pwr_hw_if.d \
./Middlewares/USBPD/usbpd_timersserver.d \
./Middlewares/USBPD/usbpd_trace.d 


# Each subdirectory must supply rules for building sources it contributes
Middlewares/USBPD/usbpd_cad_hw_if.o: C:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Middlewares/ST/STM32_USBPD_Library/Devices/STM32G0XX/src/usbpd_cad_hw_if.c Middlewares/USBPD/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32G071xx -DUSE_FULL_LL_DRIVER '-DUSBPD_PORT_COUNT=1' -D_RTOS -D_SNK -D_TRACE -D_GUI_INTERFACE -DUSBPDCORE_LIB_PD3_FULL -c -I../Core/Inc -I../USBPD/App -I../USBPD -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Drivers/STM32G0xx_HAL_Driver/Inc -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Drivers/STM32G0xx_HAL_Driver/Inc/Legacy -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Utilities/GUI_INTERFACE -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Utilities/TRACER_EMB -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Middlewares/Third_Party/FreeRTOS/Source/include -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM0 -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Middlewares/ST/STM32_USBPD_Library/Core/inc -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Middlewares/ST/STM32_USBPD_Library/Devices/STM32G0XX/inc -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Drivers/CMSIS/Device/ST/STM32G0xx/Include -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/USBPD/usbpd_cad_hw_if.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Middlewares/USBPD/usbpd_hw.o: C:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Middlewares/ST/STM32_USBPD_Library/Devices/STM32G0XX/src/usbpd_hw.c Middlewares/USBPD/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32G071xx -DUSE_FULL_LL_DRIVER '-DUSBPD_PORT_COUNT=1' -D_RTOS -D_SNK -D_TRACE -D_GUI_INTERFACE -DUSBPDCORE_LIB_PD3_FULL -c -I../Core/Inc -I../USBPD/App -I../USBPD -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Drivers/STM32G0xx_HAL_Driver/Inc -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Drivers/STM32G0xx_HAL_Driver/Inc/Legacy -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Utilities/GUI_INTERFACE -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Utilities/TRACER_EMB -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Middlewares/Third_Party/FreeRTOS/Source/include -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM0 -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Middlewares/ST/STM32_USBPD_Library/Core/inc -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Middlewares/ST/STM32_USBPD_Library/Devices/STM32G0XX/inc -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Drivers/CMSIS/Device/ST/STM32G0xx/Include -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/USBPD/usbpd_hw.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Middlewares/USBPD/usbpd_hw_if_it.o: C:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Middlewares/ST/STM32_USBPD_Library/Devices/STM32G0XX/src/usbpd_hw_if_it.c Middlewares/USBPD/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32G071xx -DUSE_FULL_LL_DRIVER '-DUSBPD_PORT_COUNT=1' -D_RTOS -D_SNK -D_TRACE -D_GUI_INTERFACE -DUSBPDCORE_LIB_PD3_FULL -c -I../Core/Inc -I../USBPD/App -I../USBPD -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Drivers/STM32G0xx_HAL_Driver/Inc -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Drivers/STM32G0xx_HAL_Driver/Inc/Legacy -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Utilities/GUI_INTERFACE -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Utilities/TRACER_EMB -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Middlewares/Third_Party/FreeRTOS/Source/include -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM0 -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Middlewares/ST/STM32_USBPD_Library/Core/inc -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Middlewares/ST/STM32_USBPD_Library/Devices/STM32G0XX/inc -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Drivers/CMSIS/Device/ST/STM32G0xx/Include -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/USBPD/usbpd_hw_if_it.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Middlewares/USBPD/usbpd_phy.o: C:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Middlewares/ST/STM32_USBPD_Library/Devices/STM32G0XX/src/usbpd_phy.c Middlewares/USBPD/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32G071xx -DUSE_FULL_LL_DRIVER '-DUSBPD_PORT_COUNT=1' -D_RTOS -D_SNK -D_TRACE -D_GUI_INTERFACE -DUSBPDCORE_LIB_PD3_FULL -c -I../Core/Inc -I../USBPD/App -I../USBPD -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Drivers/STM32G0xx_HAL_Driver/Inc -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Drivers/STM32G0xx_HAL_Driver/Inc/Legacy -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Utilities/GUI_INTERFACE -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Utilities/TRACER_EMB -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Middlewares/Third_Party/FreeRTOS/Source/include -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM0 -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Middlewares/ST/STM32_USBPD_Library/Core/inc -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Middlewares/ST/STM32_USBPD_Library/Devices/STM32G0XX/inc -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Drivers/CMSIS/Device/ST/STM32G0xx/Include -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/USBPD/usbpd_phy.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Middlewares/USBPD/usbpd_phy_hw_if.o: C:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Middlewares/ST/STM32_USBPD_Library/Devices/STM32G0XX/src/usbpd_phy_hw_if.c Middlewares/USBPD/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32G071xx -DUSE_FULL_LL_DRIVER '-DUSBPD_PORT_COUNT=1' -D_RTOS -D_SNK -D_TRACE -D_GUI_INTERFACE -DUSBPDCORE_LIB_PD3_FULL -c -I../Core/Inc -I../USBPD/App -I../USBPD -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Drivers/STM32G0xx_HAL_Driver/Inc -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Drivers/STM32G0xx_HAL_Driver/Inc/Legacy -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Utilities/GUI_INTERFACE -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Utilities/TRACER_EMB -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Middlewares/Third_Party/FreeRTOS/Source/include -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM0 -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Middlewares/ST/STM32_USBPD_Library/Core/inc -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Middlewares/ST/STM32_USBPD_Library/Devices/STM32G0XX/inc -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Drivers/CMSIS/Device/ST/STM32G0xx/Include -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/USBPD/usbpd_phy_hw_if.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Middlewares/USBPD/usbpd_pwr_hw_if.o: C:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Middlewares/ST/STM32_USBPD_Library/Devices/STM32G0XX/src/usbpd_pwr_hw_if.c Middlewares/USBPD/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32G071xx -DUSE_FULL_LL_DRIVER '-DUSBPD_PORT_COUNT=1' -D_RTOS -D_SNK -D_TRACE -D_GUI_INTERFACE -DUSBPDCORE_LIB_PD3_FULL -c -I../Core/Inc -I../USBPD/App -I../USBPD -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Drivers/STM32G0xx_HAL_Driver/Inc -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Drivers/STM32G0xx_HAL_Driver/Inc/Legacy -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Utilities/GUI_INTERFACE -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Utilities/TRACER_EMB -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Middlewares/Third_Party/FreeRTOS/Source/include -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM0 -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Middlewares/ST/STM32_USBPD_Library/Core/inc -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Middlewares/ST/STM32_USBPD_Library/Devices/STM32G0XX/inc -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Drivers/CMSIS/Device/ST/STM32G0xx/Include -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/USBPD/usbpd_pwr_hw_if.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Middlewares/USBPD/usbpd_timersserver.o: C:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Middlewares/ST/STM32_USBPD_Library/Devices/STM32G0XX/src/usbpd_timersserver.c Middlewares/USBPD/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32G071xx -DUSE_FULL_LL_DRIVER '-DUSBPD_PORT_COUNT=1' -D_RTOS -D_SNK -D_TRACE -D_GUI_INTERFACE -DUSBPDCORE_LIB_PD3_FULL -c -I../Core/Inc -I../USBPD/App -I../USBPD -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Drivers/STM32G0xx_HAL_Driver/Inc -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Drivers/STM32G0xx_HAL_Driver/Inc/Legacy -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Utilities/GUI_INTERFACE -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Utilities/TRACER_EMB -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Middlewares/Third_Party/FreeRTOS/Source/include -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM0 -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Middlewares/ST/STM32_USBPD_Library/Core/inc -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Middlewares/ST/STM32_USBPD_Library/Devices/STM32G0XX/inc -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Drivers/CMSIS/Device/ST/STM32G0xx/Include -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/USBPD/usbpd_timersserver.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Middlewares/USBPD/usbpd_trace.o: C:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Middlewares/ST/STM32_USBPD_Library/Core/src/usbpd_trace.c Middlewares/USBPD/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32G071xx -DUSE_FULL_LL_DRIVER '-DUSBPD_PORT_COUNT=1' -D_RTOS -D_SNK -D_TRACE -D_GUI_INTERFACE -DUSBPDCORE_LIB_PD3_FULL -c -I../Core/Inc -I../USBPD/App -I../USBPD -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Drivers/STM32G0xx_HAL_Driver/Inc -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Drivers/STM32G0xx_HAL_Driver/Inc/Legacy -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Utilities/GUI_INTERFACE -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Utilities/TRACER_EMB -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Middlewares/Third_Party/FreeRTOS/Source/include -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM0 -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Middlewares/ST/STM32_USBPD_Library/Core/inc -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Middlewares/ST/STM32_USBPD_Library/Devices/STM32G0XX/inc -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Drivers/CMSIS/Device/ST/STM32G0xx/Include -IC:/Users/HP/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.1/Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/USBPD/usbpd_trace.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"

